// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for web - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUAIXEJScgczFWDsWhA5hYfkMyzpOvVyA',
    appId: '1:630927949869:android:5298c3f804712498ce38a4',
    messagingSenderId: '630927949869',
    projectId: 'redux-cfadf',
    storageBucket: 'redux-cfadf.firebasestorage.app',
  );

  static FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCC26A-kNTZFBLdi-_EWRZoQbIdmoJ8J50",
    authDomain: "redux-cfadf.firebaseapp.com",
    projectId: "redux-cfadf",
    storageBucket: "redux-cfadf.firebasestorage.app",
    messagingSenderId: "630927949869",
    appId: "1:630927949869:web:c7cec980eab6532ece38a4",
    measurementId: "G-DM357X8B8F",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ZWwDI2QWHZ-jPb2Au2EYoWc-wvM2UF0',
    appId: '1:630927949869:ios:09f7dc69c2c55336ce38a4',
    messagingSenderId: '630927949869',
    projectId: 'redux-cfadf',
    storageBucket: 'redux-cfadf.firebasestorage.app',
    iosBundleId: 'com.example.eCommercApp',
  );
}
